version: '3.6'

services:
  db:
    #platform: linux/x86_64 # for Mac M1 (ohne Plattform für Intel Macs)
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: coworkingspace
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: entrydb
      MYSQL_ROOT_PASSWORD: 123456
